#!/bin/python

import sys


def palindrome_number():
    _range = xrange(100, 1000)
    palindrome = None
    for i in _range:
        for j in _range:
            prod = i * j
            if str(prod) == str(prod)[:-1]:
                if prod > palindrome:
                    palindrome = prod
    return palindrome

print(palindrome_number())
